#!/usr/bin/env python3
import os
import sys
import argparse
import json
import time

def main():
    parser = argparse.ArgumentParser(description="Closed-Loop Failure Ingestion Utility")
    parser.add_argument("--suite-path", required=True, help="Path to test_suite.json")
    parser.add_argument("--input", required=True, help="The original input that led to failure")
    parser.add_argument("--bad-output", required=True, help="The bad output generated by the LLM")
    parser.add_argument("--reason", required=True, help="Reason for rejection / correct expectations")
    args = parser.parse_args()

    suite_path = os.path.abspath(args.suite_path)
    if not os.path.exists(suite_path):
        print(f"[ERROR] Test suite file not found: {suite_path}")
        sys.exit(1)

    try:
        with open(suite_path, "r") as f:
            suite = json.load(f)
    except Exception as e:
        print(f"[ERROR] Failed to read test suite: {e}")
        sys.exit(1)

    test_cases = suite.get("test_cases", [])
    
    # Generate new test case ID
    case_id = f"case_{int(time.time())}"

    # Build new test case structure
    new_case = {
        "id": case_id,
        "input": args.input,
        "expected_criteria": args.reason,
        "bad_output_reference": args.bad_output,
        "baseline_score": 1.0,  # Target baseline represents resolving this error
        "timestamp": int(time.time())
    }

    test_cases.append(new_case)
    suite["test_cases"] = test_cases

    try:
        with open(suite_path, "w") as f:
            json.dump(suite, f, indent=2)
        print(f"[SUCCESS] Appended new regression check '{case_id}' to the test suite.")
        print(f"  Input: {args.input[:50]}...")
        print(f"  Expected Fix: {args.reason}")
    except Exception as e:
        print(f"[ERROR] Failed to save test suite: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
